//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApplicationWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBAPI_Tree
    {
        public int NodeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ItemName { get; set; }
    }
}
